config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'appointments/index'
  get 'appointments/new'
root 'patients#index'

  resources :patients
  resources :physicians do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_physician
  

  def index
    @appointments = @physician.appointments.order(:date, :time)
  end


    def new
      @appointment = @physician.appointments.new
    end


  def create
    @appointment = @physician.appointments.new(appointment_params)
    if @appointment.save
      redirect_to physician_appointments_path(@physician)
    else
      render :new
    end
  end

  def destroy
    @physician.appointments.find(params[:id]).destroy
    redirect_to physician_appointments_path
  end

 private
   def set_physician
     @physician = Physician.find(params[:physician_id]) 
   end

   def appointment_params
     params.require(:appointment).permit(:name, :patient_id, :date, :time)
   end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else
      render :new
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name)
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
before_action :set_physician, only: [:show, :destroy]

  def index
    @physicians = Physician.all
  end

  def show
  end

  def new
    @physician = Physician.new
  end

  def create
    @physician = Physician.new(physician_params)

    if @physician.save
      redirect_to @physician
    else
      render :new
    end
  end

  def destroy
    @physician.destroy
    redirect_to physicians_path
  end

private

  def set_physician
    @physician = Physician.find(params[:id])
  end

  def physician_params
    params.require(:physician).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/index.html.erb
<h1><%= @physician.name %>: Appointments</h1>
<%= link_to 'Add Appointment', new_physician_appointment_path(@physician), class: "ui inverted blue button" %>
<hr />

<h2>Appointments</h2>
<ul>
<table class="ui celled table">
<thead>
<tr>
<th>Patient Name <i class="users icon"></th>
<th>Appointment Date <i class="calendar icon"></th>
<th>Appointment Time <i class="clock icon"></th>
<th>Remove <i class="trash icon"></th>
</tr>
</thead>

<tbody>
  <% @appointments.each do |appt| %>
    <tr>
      <td><%= appt.patient.name %></td>
      <td><%= appt.date.strftime('%a, %b, %d, %Y') %></td>
      <td><%= appt.time.strftime('%l:%M %p') %></td>
      <td><%= link_to 'Remove', physician_appointment_path(@physician, appt), method: :delete, class: "ui button" %></td>
    </tr>
  <% end %>
</tbody>
</table>
      <br />

app/views/appointments/new.html.erb
<h1>Add Appointment</h1>
<%= form_with(model: [@physician, @appointment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :patient %>
  <%= f.select :patient_id, Patient.all.collect { |p| [p.name, p.id] } %>
  <br />
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br />
  <%= f.label :time %>
  <%= f.time_field :time %>
  
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="ui pointing menu">
  <%= link_to 'Physicians', physicians_path, class: "item" %>
  
  <%= link_to 'Patients', patients_path, class: "item"  %>
  

  <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "ui inverted blue button" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorOfficeScheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class='ui container'>
    <%= yield %>
  </div>
  </body>
</html>

app/views/patients/index.html.erb
<h1> Patients</h1>
<hr />
<h2><%= @patients.length <= 0 ? "No Patients" : "" %></h2> 
<%= link_to 'Add Patient', new_patient_path, class: "ui inverted blue button" %>
<table class="ui celled table">
<thead>
<tr>
<th> Patient Name </th>
<th> Delete </th>
</tr>
</thead>
<tbody>
<tr>
  <% @patients.each do |patient| %>
   
     <td> <%= link_to patient.name, patient%></td>
   <td><%= link_to 'Delete ', [@physician, patient], method: :delete, class: "ui right floated red button inverted" %> </td>
    
 
  </tr>
   <% end %>
</tbdy>
</table>

app/views/patients/new.html.erb
<h1>Add Patient</h1>
<%= form_with(model: @patient, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/patients/show.html.erb
<h1><%= @patient.name %>: Doctors</h1>
<hr />
<table class="ui celled table">
<thead>
<tr>
<th>Physicians</th>
<th> Specialty </th>
</tr>
</thead>
<tbody>
  <tr>
    <% @patient.physicians.each do |physician| %>
        <td><%= link_to physician.name, physician %></td>
        <td> Specialty </td>
  </tr>
   <% end %>
  </tbody>
</table>
<br />
<br />
<br />
<%= link_to 'Delete Patient', @patient, method: :delete, class: "ui red button inverted" %>

app/views/physicians/index.html.erb
<h1> Physicians</h1>  
<hr />
<a><%= link_to 'Add Physician', new_physician_path, class: "ui inverted blue button"  %></a>
<table class="ui celled table">
  <h2><%= @physicians.length <= 0 ? "No Physicians" : "" %></h2> 
  <thead>
  <tr>
  <th> Physicians </th>
  <th> Specialty </th>
  </tr>
  </thead>
  <tbody>
  
    <% @physicians.each do |physician| %>
    <tr>
    <td><%= link_to physician.name, physician %></td>
    <td> <%= link_to 'Delete ', [@patient, physician], method: :delete, class: "ui right floated red button inverted" %> </td>
    <% end %>
  </tr>
  </tbody>
</table>

app/views/physicians/new.html.erb
<h1>Add Physician</h1>
<%= form_with(model: @physician, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/physicians/show.html.erb
<h1><%= @physician.name %></h1>
<hr />

<table class="ui big celled table">
<thead>
  <tr>
  <th><h2>Patients</h2></th>
  <th> Date </th>
  <th> Time </th>
  </tr>
</thead>
  <tbody>
  <% @physician.appointments.each do |appt| %>
    <tr>
      <td><%= link_to appt.patient.name, patient_path %></td>
      <td><%= appt.date.strftime('%a, %b, %d, %Y') %></td>
      <td><%= appt.time.strftime('%l:%M %p') %></td>
    </tr>
  </tbody>
      <% end %>
</table>
<br />
<%= link_to 'Appointments', physician_appointments_path(@physician), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to 'Delete Physician', @physician, method: :delete, class: "ui red button inverted" %>